### ISSUE TITLE
whether there is an opportunity to work in batch mode?

### ISSUE THREAD

**Issue by truskovskiyk** [jcjohnson/densecap#36]
Hi! 
I tried to rewrite run_model.lua script to work in batch mode, but get the error 

./densecap/DenseCapModel.lua:244: assertion failed!
stack traceback:
	[C]: in function 'assert'
	./densecap/DenseCapModel.lua:244: in function 'forward'
	./densecap/DenseCapModel.lua:321: in function 'forward_test'

Also, I see this comment https://github.com/jcjohnson/densecap/blob/master/densecap/DenseCapModel.lua#L215

So whether there is an opportunity to work in batch mode?
Thanks

**Comment by jcjohnson** [comment]
I think that running in batch mode will require nontrivial changes.

The current design is that the network accepts a single image of shape (1, C, H, W); the Localization Layer produces N regions of interest for the single image, and these region proposals end up in the minibatch dimension. If you wanted to run in batch mode, each image could potentially give rise to multiple regions of interest; you would need to keep track of the mapping between input image indexes and region proposal indexes, which would require modifying a number of files.

**Comment by truskovskiyk** [comment]
@jcjohnson thanks

**Comment by abhinavagarwalla** [comment]
@truskovskiyk Was your attempt successful in running batch mode ?

I also have a large data, which would take a lot of time if the batch size is 1. I was also trying to modify the code, but got stuck at Localization Layer. Particularly at expandAs since it only supports singleton expansion.
A trivial work around would be to just loop through all CNN features, but that's a bad idea. Any other thoughts ?

**Comment by truskovskiyk** [comment]
@abhinavagarwalla Unfortunately, I don't create batch mode. For my project now I use https://github.com/tensorflow/models/tree/master/im2txt which show greater improvements, wich shows greater result when train model with CNN
